# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps: 
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: apt update && echo "5" | apt install neofetch curl tar xz -y && sh <(curl -L https://nixos.org/nix/install) --no-daemon && nix-channel --update && nix-env --upgrade && df -h && nix-env -iA nixpkgs.code-server && code-server --bind-addr 127.0.0.1:6969 >/dev/null && curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list && apt update && apt install ngrok -y && ngrok config add-authtoken ${NGK_KEY} && ngrok http http://localhost:6969



