# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: apt update && apt install neofetch git wget curl make gcc golang -y && df -h && neofetch && wget https://github.com/jkuri/bore/releases/download/v0.4.2/bore-server_linux_amd64 && chmod +x bore-server_linux_amd64 && BORE_DOMAIN=bore.digital BORE_HTTPADDR=0.0.0.0:80 BORE_SSHADDR=0.0.0.0:2200 ./bore-server_linux_amd64 

