# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps: 
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:W7rZZefhSSFYS07C0ZHMk/MTcHErwxGZfRbtlTpLRVY"
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: apt update && apt install neofetch git wget curl make gcc golang -y && df -h && neofetch && ssh -R 80:localhost:3000 serveo.net


