version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:mantic-20240530
    steps: 
      - run:
          name: Install Deps
          command: |
            apt update
            echo "5" | apt install bc python3 bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk openjdk-8-jre -y 
      - run:
          name: Setup work directories
          command: |
            mkdir -p /work
            mkdir -p /work/bin 
            mkdir -p /work/android/lineage
      - run:
          name: Install repo
          command: |
            curl https://storage.googleapis.com/git-repo-downloads/repo > /work/bin/repo 
            chmod a+x /work/bin/repo
            ccache -M 50G
      - run:
          name: Build Prep
          command: |
            cd /work/android/lineage
            /work/bin/repo init -u https://github.com/atv-tank/manifest.git -b cm-14.1 && ls
            /work/bin/repo sync
            git clone https://github.com/atv-tank/android_device_amazon_tank -b cm-14.1 device/amazon/tank
            git clone https://github.com/atv-tank/android_kernel_amazon_mt8127 -b cm-14.1 kernel/amazon/mt8127
            git clone https://github.com/atv-tank/vendor_amazon_tank -b exp vendor/amazon/tank && ls
            export USE_CCACHE=1
            export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
      - run:
          name: Build ROM
          command: |
            cd ~/android/lineage && ls
            ccache -M 50G
            source build/envsetup.sh 
            ccache -M 50G
            lunch lineage_tank userdebug
            ccache -M 50G
            croot
            ccache -M 50G
            brunch tank
            ls
            cd $OUT && ls
            curl -F "file=@lineage*" https://temp.sh/upload
