# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:master
    steps: 
      - run:
          name: Build an artifact
          command: nix-channel --update && nix-env --upgrade && df -h && nix-env -iA nixpkgs.code-server && nix-env -iA nixpkgs.curl && code-server --bind-addr 127.0.0.1:6969 >/dev/null && nix-env -iA nixpkgs.ngrok && ngrok config add-authtoken ${NGK_KEY} && ngrok http http://localhost:6969


# apt update && echo "5" | apt install neofetch curl tar wget -y && wget http://security.ubuntu.com/ubuntu/pool/main/x/xz-utils/xz-utils_5.2.4-1ubuntu1.1_amd64.deb && dpkg --install --force-depends ./xz-utils_5.2.4-1ubuntu1.1_amd64.deb && apt-get install --fix-broken --assume-yes && sh <(curl -L https://nixos.org/nix/install) --daemon && 
# curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list && apt update && apt install ngrok -y 
